[target.'cfg(any(target_arch = "xtensa", target_arch = "riscv32"))']
runner = "espflash flash --monitor"


[env]
ESP_LOGLEVEL = "DEBUG"
ESP_LOGTARGETS = "esp_wifi::compat::timer_compat=warn,esp_wifi::tasks=info"

[build]
rustflags = [
  "-C",
  "link-arg=-Tlinkall.x",

  # # Required to obtain backtraces (e.g. when using the "esp-backtrace" crate.) on riscv32imc targets.
  # # NOTE: May negatively impact performance of produced code
  "-C",
  "force-frame-pointers",
]

target = "riscv32imc-unknown-none-elf"

[unstable]
build-std = [
  "alloc",
  "core",
]
